/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LoongStorePolicy */

#ifndef _Included_LoongStorePolicy
#define _Included_LoongStorePolicy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LoongStorePolicy
 * Method:    setAllocAffinity
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_LoongStorePolicy_setAllocAffinity
  (JNIEnv *, jclass, jstring);

/*
 * Class:     LoongStorePolicy
 * Method:    getIstInfo
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_LoongStorePolicy_getIstInfo
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     LoongStorePolicy
 * Method:    getIpNodeMap
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_LoongStorePolicy_getIpNodeMap
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
