/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LoongStorePolicy_IstInfo */

#ifndef _Included_LoongStorePolicy_IstInfo
#define _Included_LoongStorePolicy_IstInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
